name: hyuga_app
description: Hyuga App - Find your ideal hangout location.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+16

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # firebase_storage: ^5.0.0
  firebase_storage: 
  # image_picker: 0.6.7+12
  image_picker: ^0.8.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # font_awesome_flutter: ^8.8.1
  font_awesome_flutter:  
  # cupertino_icons: ^0.1.2
  cupertino_icons: 
  # firebase_auth: ^0.18.0+1
  firebase_auth:
  # cloud_firestore: ^0.14.0+2
  cloud_firestore: ^3.1.7
  # location: ^3.0.2
  location: 
  # google_maps_flutter: ^0.5.24+1
  google_maps_flutter:
  # latlong: ^0.6.1
  # latlong:
  maps_toolkit: ^2.0.0
  # provider: ^4.0.5
  provider: 
  # rxdart: ^0.24.0
  rxdart:
  # google_sign_in: ^4.4.4
  google_sign_in: 
  #flutter_facebook_login: ^3.0.0
  # http: ^0.12.1
  #http: 
  # qr_flutter: ^3.2.0
  qr_flutter: 
  # firebase_analytics: ^5.0.16
  firebase_analytics: 
  # apple_sign_in: ^0.1.0 #available only for IOS
  # apple_sign_in:
  sign_in_with_apple:
  # geocoder: ^0.2.1
  # geocoder:
  geocode: ^1.0.1
  # url_launcher: ^5.5.1
  url_launcher: 
  # firebase_messaging: ^7.0.0
  firebase_messaging: 
  # expansion_card: ^0.1.0
  expansion_card:
  # qr_code_scanner: ^0.0.13
  qr_code_scanner:
  # animations: ^1.1.2
  animations: 
  # firebase_database: ^4.1.0
  firebase_database:
  #square_in_app_payments: ^1.5.1
  # google_ml_kit: ^0.0.3+1
  google_ml_kit: 
  # sliding_up_panel: ^1.0.2	
  sliding_up_panel:	
  # flutter_facebook_auth: ^1.0.2
  flutter_facebook_auth:
  in_app_purchase: 
  #adapty_flutter:
  #firebase_app_check:
  fake_cloud_firestore:



  
# Commented
# dependency_overrides:
#   firebase_core: 0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:           # new
    sdk: flutter              # new
  test: ^1.14.4               # new


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/empty-profile.png
    - assets/images/google-logo-icon.png
    - assets/images/hyuga-logo.png
    - assets/images/stars.png
    - assets/images/wine-street-logo.png
    - assets/images/pins/ios/wine-street-logo-pin.png
    - assets/images/pins/android/wine-street-logo-pin.png
    - assets/images/wine_icon1.png
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
